version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: notif_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:7
    container_name: notif_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: notif_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notifications?schema=public
      REDIS_URL: redis://redis:6379
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      VAPID_PUBLIC_KEY: BCay7hezqZDlyUgzsj1iq8TgQSbKkBv5Zk2Yr--UaB8u6p-rkLgudfnWZ7qKl8CPdccWgqhu46i5IreeqwkL73M
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: notif_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_VAPID_PUBLIC_KEY: BCay7hezqZDlyUgzsj1iq8TgQSbKkBv5Zk2Yr--UaB8u6p-rkLgudfnWZ7qKl8CPdccWgqhu46i5IreeqwkL73M
      REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:3000"

  # Optional: mailhog for local email testing
  mailhog:
    image: mailhog/mailhog
    container_name: notif_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
